Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-stretch64"

  (8000..8100).step(1) do |n|
    config.vm.network "forwarded_port", guest: n, host: n, auto_correct: true
  end

  config.vm.network "forwarded_port", guest: 22, host: 2222

  config.vm.provider "virtualbox" do |v|
    v.name = "debian-9.3.0-amd64"
    v.memory = "6144"
    v.gui = true
    v.cpus = 4
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "60"]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    v.customize ["modifyvm", :id, "--ostype", "Debian_64"]
  end

  # config.vm.provision "shell", privileged: true, path: "provision/setup.sh"

end
